### PR TITLE
lots of changes

### PR DESCRIPTION
**Pull request by jacobbearden**
lots of code quality/code structuring improvements, sped up/improved the server status fetching, made the nav links auto generate based on the pages available, some slight appearance tweaks, made the footer stick to the bottom, `_data`-itized more stuff, etc

i'd just load it up locally and poke around to see everything if i were you 😛 

~~i still need to readd dark theme support so feel free to keep this PR open till i do that some time in the next few days~~

Screen Shot 2020-01-22 at 11 49 49 PM
Screen Shot 2020-01-22 at 11 50 01 PM
Screen Shot 2020-01-22 at 11 50 15 PM

### CODE REVIEW

**Comment by jacobbearden** [comment]
Screen Shot 2020-01-23 at 12 13 52 AM

**Comment by Brottweiler** [comment]
I've checked this out locally and a few things:

- The carousel don't switch images, it's one static image for me.
- The frontpage headline is very small, and the text under it is very very skinny for me;
    
image

Compare this to the current website:
image

The name at the top left has a different font, which makes me think I am simply, for some reason, missing the proper font and can't display the website as it is intended to be displayed. This might be the issue with the text in the images, but I also want to point out that the "Community" is in red and not gray like we have on the current website.

- The playerheads on the play page in your screenshot, show 6 on each row. I have 5 heads on the 1st and 2nd row, and two heads on the 3rd row, I don't see why this happens..

- The playerheads on the staff page, and probably the play page too, should show helmets, because they currently don't.

- The menu at the top right, you cannot see which page you are on. If you are on the Play page, the Rules and Staff links should be darker to indicate you are currently on the Play page.

**Comment by jacobbearden** [comment]
@Brottweiler 
1. its still a slider for me, do you have console errors or anything from it?
2. it was made a little bit smaller, but its also setting the size in a different manner now, what is your browser zoom at? that might affect it. (I did make it slightly bigger in the above commit though) I made the smaller text a bit thicker too.
3. Its now set up to use a "system" font stack thats pretty widely recommended these days
```-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"```
so it just goes down this list until you have one of them, which might be why yours looks different than mine. If theres a preferred font we can talk about what to use instead.
4. Fixed the colors on the heading
5. Fixed how I was breaking the images into two rows, should work now.
6. I added the `overlay` attributes to where there are player images, it can't be added in the url in the yml though.
7. Fixed

**Comment by Brottweiler** [comment]
Oh it slides now, so we're good, not sure what was the problem before.

I do have Roboto installed, so I assume that's the font that's getting used for me. I suppose I am fine with that though, but Lato would be nice but it would need to be included in the head like on current website.

I think it looks a bit weird when `1.15.2` gets a linebreak here, can we improve this?
image

The carousel is not center on mobile
image

This looks a bit weird when the image isn't center, can it be improved? Also notice the `hr` at the bottom going through the badge.
image

When mobile screen isn't very wide, the footer goes through the content. This is probably what is happening in the screenshot above, as well. I made it extremely slim here, but only to make it obvious.
image

**Comment by jacobbearden** [comment]
@Brottweiler give it a spin now

**Comment by Brottweiler** [comment]
Great! I want to merge this, but I have a couple of last pointers.

I noticed on the play page, the map.png is scaled down. Did you do this because it looked better? Could we display the map image at full size or would that not look good?

On the current website, you can hover over the map name and it will display the objective of that map. Are you able to reintroduce that? Not sure if you had a reason for removing it?

And last, Chrome is giving some *warnings* about cookies. To avoid stuff breaking in the future, could they be resolved? I don't seem to always get these warnings in the console though. I got one related to FontAwesome as well but they don't always show, not sure if it's a problem.

```
A cookie associated with a cross-site resource at http://crafatar.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`.

**Comment by jacobbearden** [comment]
@Brottweiler 

> I noticed on the play page, the map.png is scaled down. Did you do this because it looked better? Could we display the map image at full size or would that not look good?

It is sized based on screen width, which is the only sure way for it to not look out of place on different screen sizes. I can tweak it to be a bit better though.

> On the current website, you can hover over the map name and it will display the objective of that map. Are you able to reintroduce that? Not sure if you had a reason for removing it?

I felt it was redundant given the tags describing the map. If it's really wanted I think it'd be better to just display it below the map name as text rather than as a tooltip.

> And last, Chrome is giving some warnings about cookies. To avoid stuff breaking in the future, could they be resolved?

That's up to crafatar and fontawesome to fix as it's on their end.

**Comment by Brottweiler** [comment]
@jacobbearden 
>It is sized based on screen width, which is the only sure way for it to not look out of place on different screen sizes. I can tweak it to be a bit better though.

I see, but regardless how large I make my browser window, the map image does not show at full size. Only on mobile, the image becomes larger, but then it's upscaled (which should be fine). I just think it would make sense that the image shows at 100% scaling when browser window is largest.

> I felt it was redundant given the tags describing the map. If it's really wanted I think it'd be better to just display it below the map name as text rather than as a tooltip.

Actually this is a good point. I'm fine with the objective not showing!

**Comment by jacobbearden** [comment]
@Brottweiler fixed

**Comment by Brottweiler** [comment]
Thanks a lot!

**Pull request merged**
